apiVersion: v1
kind: Pod
metadata: 
  name: pod-dodo
  namespace: default
spec:
  nodeSelector:
    coder: devops
  containers:
  - image: nginx
    name: dodo-cont1
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 300M
        
  
