apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-dodo
  namespace: default
spec: 
  replicas: 2
  strategy: 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector: 
    matchExpressions:
    - key: coder
      operator: In
      values:
      - dodo
  template:
    metadata:
      labels:
        coder: dodo
      name: pod-dodo
      namespace: default
    spec:
      affinity:
        nodeAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions: 
          #     - operator: In
          #       key: coder3
          #       values: 
          #       - devops3
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:  
              matchExpressions:
              - operator: In
                key: coder4
                values: 
                - devops4
            weight: 1

      containers:
      - image: nginx
        name: cont-dodo
        ports:
        - containerPort: 80
        volumeMounts: 
        - mountPath: /usr/share/nginx/html
          name: vol-dodo
      nodeSelector: 
        coder1: devops1
      volumes: 
      - name: vol-dodo
        persistentVolumeClaim:
          claimName: pvc-dodo

      